### ISSUE TITLE
Cannot open playlist

### ISSUE THREAD

**Issue by FirstLoveLife** [nicehiro/netease-music#1]
The echo area always promot:
```
Contacting host: localhost:3000
```
But cannot enter into the playlist
![image](https://user-images.githubusercontent.com/37442588/43673881-a6768160-97fc-11e8-8c54-05cc97fc192f.png)

I tried `netease-music-login:
> funcall-interactively: Wrong number of arguments: #[(username password) "ÅÆ	
#\"ÇÈ!!)" [netease-music-login-url netease-music-login-args username password json netease-music-request format message netease-music-set-user-id] 6 ("/home/chenli/.emacs.d/elpa/netease-music-20180429.1822/netease-music.elc" . 15770) nil], 0

**Comment by nicehiro** [comment]
You can just switch buffer to 'netease-music-playlist' and you can see this playlist's songs. Sorry for late response.

**Comment by FirstLoveLife** [comment]
@nicehiro Thanks, but that buffer has no list:
![image](https://user-images.githubusercontent.com/37442588/45398588-66641a80-b677-11e8-9b62-0fdf0f49fd84.png)

**Comment by nicehiro** [comment]
Yes...Because netease music API updated. I'm working on it. When I fix it, I'll let you know. Sorry for that. :sleepy:

**Comment by FirstLoveLife** [comment]
Thanks for your awesome work!

**Comment by nicehiro** [comment]
I've fixed the issue, but melpa will udpate it later. Maybe you need to be patient.

**Comment by FirstLoveLife** [comment]
I will use quelpa

**Comment by FirstLoveLife** [comment]
Problem fixed
