### ISSUE TITLE
私人fm和like功能用不了啊

### ISSUE THREAD

**Issue by toure00** [nicehiro/netease-music#3]
![image](https://user-images.githubusercontent.com/33457469/59238991-a110d880-8c32-11e9-82d3-42ca65842585.png)
你好，我现在出现了这样的问题，出错的这几个都是在emacs里调用方法发起的请求，我把这个请求链接复制到浏览器再发一遍，显示的都是ok

补充一下，每日推荐和like会出错卡死，
私人fm有时能请求成功，不过请求成功会在emacs里报别的错

我的电脑是OSX10.14，emacs配置是spaceamcs
![image](https://user-images.githubusercontent.com/33457469/59239836-8724c500-8c35-11e9-86d2-abc309457d4f.png)

**Comment by toure00** [comment]
不好意思，不是网络请求的问题，是我没执行登录的代码，执行之后网络请求没问题了，like功能也没问题，不过日推和私人fm在emacs这边还是显示不出来

**Comment by nicehiro** [comment]
@toure00 你好，这个项目我也好久没用了，估计是那边api更新了，之后有空会改过来的。或者你也可以试着改一下的。:smile:

**Comment by nicehiro** [comment]
喜欢歌曲 这个接口仍然有概率发生问题，但私人fm应该可以了。

所以目前把 喜欢歌曲 这个功能去掉了。
