### ISSUE TITLE
netease-music-jump-into 命令失效

### ISSUE THREAD

**Issue by drcxd** [nicehiro/netease-music#4]
如题，按照文档安装配置成功，可以显示歌单列表；但是却无法用`netease-music-jump-into`命令进入歌单，也即是无法显示歌曲列表。

api server显示的输出都是[OK]，但是emacs buffer没有刷新。

补充，`netease-music-playlist`的buffer被创建出来了，但是Song List里面没有内容，是API返回的东西变了？

**Comment by nicehiro** [comment]
buffer 会自动创建，但不会主动跳转的，你需要手动切换。

刚刚我测试了最新的API，没有发现问题，可以正常播放音乐和显示 Song List。

**Comment by drcxd** [comment]
我主动切换过去，`Song List`确实还是空的。我的网络环境是在墙外的，是否是受这个影响？另外，我是在windows subsystem for linux 下使用的emacs。

**Comment by nicehiro** [comment]
国外好像确实会出现问题。请查看 [NeteaseMusicAPI文档](https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=%e5%ae%89%e8%a3%85)解决。

![](https://user-images.githubusercontent.com/17773634/69952894-1bac1800-1533-11ea-8789-c93427793a1d.png)

**Comment by drcxd** [comment]
headers里面加了X-Real-IP 字段也还是不行，看来在国外享受不了这个了。
